# Default values for infinitymaps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  replicaCount: 1

  image:
    repository: registry.awesome-it.de/infinity/backend
    pullPolicy: Always

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  config:
    mongoHost: mongodb-headless
    mongoPort: "27017"
    mongoDatabase: infinity
    nodeEnv: production
    port: 3000
    env: []

  podSecurityContext: {}
  #   fsGroup: 2000

  securityContext: {}
  #   capabilities:
  #     drop:
  #     - ALL
  #   readOnlyRootFilesystem: true
  #   runAsNonRoot: true
  #   runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  # secretName:
  metrics:
    enabled: false
    interval: 10s

  ingress:
    enabled: false
    annotations: {}
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"
    hosts: []
    #  - host: chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  annotations: {}

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

backup:
  enabled: false
  schedule: "15 0 * * *"
  dateFormat: "%Y%m%d-%H%M"
  image:
    repository: registry.awesome-it.de/infinity/mongodb-backup
    pullPolicy: Always
    tag: latest
  imagePullSecrets: []
  compressionLevel: 9
  restic: {}
  #  password:
  #  secretName:

  s3: {}
  #  accessKey: ""
  ### contains s3 secret
  #  secretKey: ""
  #  secretName: ""
  #  repository: ""


frontend:
  replicaCount: 1

  image:
    repository: registry.awesome-it.de/infinity/frontend
    pullPolicy: Always

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart.example.com
        paths: ["/"]
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  annotations: {}

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

mongodb:
  enabled: false
  auth:
    database: infinity
    username: infinity
