apiVersion: v1
kind: Service
metadata:
  name: {{ include "infinitymaps.fullname" . }}-backend-websocket
  labels:
    {{- include "infinitymaps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: backend-websocket
    {{- include "infinitymaps.selectorLabels" . | nindent 4 }}
