# start the infrastructure for local e2e tests
version: "2"
services:

  chrome:
#    image: selenium/node-chrome:4.0.0-beta-3-20210426
    image: selenium/node-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "5900:5900"
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: 4444

  selenium-hub:
#    image: selenium/hub:4.0.0-beta-3-20210426
    image: selenium/hub:latest
    ports:
      - "4444:4444"
